# Generated by Django 5.2.7 on 2025-11-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenmanager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecipeRequirements",
            new_name="RecipeRequirement",
        ),
        migrations.RenameField(
            model_name="reciperequirement",
            old_name="ingredients",
            new_name="ingredient",
        ),
    ]
