# Generated by Django 5.2.7 on 2025-11-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenmanager", "0002_rename_reciperequirements_reciperequirement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="menu_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kitchenmanager.menuitem",
            ),
        ),
    ]
