# Generated by Django 5.2.7 on 2025-11-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchenmanager", "0003_alter_purchase_menu_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciperequirement",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="kitchenmanager.menuitem",
            ),
        ),
    ]
